name: Análisis con SonarCloud

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  

jobs:
  sonar:
    name: Analizar con SonarCloud
    runs-on: ubuntu-latest  

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v11
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Ejecutar análisis en SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn verify sonar:sonar \
            -Dsonar.projectKey=TU_PROYECTO \
            -Dsonar.organization=TU_ORGANIZACION \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

